### ISSUE TITLE
Pressing "I" on world creation screen crashes game

### ISSUE THREAD

**Issue by Partonetrain** [Franckyi/ItemEditorGUI#7]
I was going to have my world be named with an "I" in it, but it looks like it crashes when I hit "I" at all. If I had to guess, it's listen for hitting that key on the menu where it shouldn't.

---- Minecraft Crash Report ----
// Why is it breaking :(

Time: 2/19/17 11:25 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.franckyi.itemeditor.event.ModEventHandler.onKeyPressed(ModEventHandler.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_ModEventHandler_onKeyPressed_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:522)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.franckyi.itemeditor.event.ModEventHandler.onKeyPressed(ModEventHandler.java:51)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_52_ModEventHandler_onKeyPressed_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:522)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.GuiCreateWorld
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1125029832 bytes (1072 MB) / 1827667968 bytes (1743 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2232 11 mods loaded, 11 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2232.jar) 
	UCHIJA	forge{13.20.0.2232} [Minecraft Forge] (forge-1.11.2-13.20.0.2232.jar) 
	UCHIJA	customnpcs{1.11.2} [CustomNPCs] (CustomNPCs_1.11.2_beta(22jan17).jar) 
	UCHIJA	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UCHIJA	itemeditor{1.11.x-0.1.0.0} [Item Editor GUI] (itemeditor-1.11.x-0.1.0.0.jar) 
	UCHIJA	jei{4.2.6.238} [Just Enough Items] (jei_1.11.2-4.2.6.238.jar) 
	UCHIJA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJA	variedcommodities{1.11.2} [Varied Commodities] (VariedCommodities_1.11.2(22jan17).jar) 
	UCHIJA	worldedit{6.1.6} [WorldEdit] (worldedit-forge-mc1.11-6.1.6-dist.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 372.70' Renderer: 'GeForce GTX 970M/PCIe/SSE2'
	Launched Version: forge-13.20.0.2232
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970M/PCIe/SSE2 GL version 4.5.0 NVIDIA 372.70, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz

**Comment by skyecodes** [comment]
Thanks for reporting this error. It will be fixed soon.
